### ISSUE TITLE
Speicher funktioniert nicht korrekt.

### ISSUE THREAD

**Issue by gandafl** [iti-luebeck/RTeasy2#25]
Bei der Generierung des Speichers werden nur 2^n -1 Speicherstellen angelegt. 
Außerdem funktioniert das Abspeichern des Speicherinhalts nicht mehr. Es öffnet sich anstelle des Speichern-Dialogs das Öffnen-Fenster.

Testcode:
declare register AR(3:0), DR(7:0);
declare memory MEM(AR, DR);

AR <- 0;

![rt mem bug](https://cloud.githubusercontent.com/assets/5111526/11655991/56967ac0-9db2-11e5-91c5-49932ff0338d.PNG)

**Comment by gandafl** [comment]
Ich habe eine einfache Lösung für beide Fehler gefunden.
Die beiden Fehler befinden sich im Modul "GUI", Paket "org.desert.gui":

Um die Anzahl der Speicherzellen zu korrigieren, muss Zeile 55 in der Datei MemoryFrameTableModel.java geändert werden:
```java
public class MemoryFrameTableModel extends AbstractTableModel {
    memaw = m.getAddrWidth();
    taddr = new boolean[memaw];
    memdw = m.getDataWidth();
-    memSize = new BigInteger("2").pow(memaw).subtract(BigInteger.ONE);
+    memSize = new BigInteger("2").pow(memaw);
    curPage = BigInteger.ONE;
    offset = BigInteger.ZERO;
    BigDecimal memSizeBD = new BigDecimal(memSize).divide(new BigDecimal("" + pageSize)).setScale(0, RoundingMode.UP);
    ...
```

Um den Speicherdialog zum Abspeichern des Memorys zu erhalten, genügt es die Zeile 311 in der Datei MemoryViewerTopComponent.java wie folgt anzupassen:
```java
 private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    try {
-        File f = FileOperationsHelper.openFileDialog();
+        File f = FileOperationsHelper.saveFileDialog(null);
             
        if(f == null) {
            return;
    ...
```

**Comment by JodderHL** [comment]
> Bei der Generierung des Speichers werden nur 2^n -1 Speicherstellen angelegt.

Correct - included your solution

> Um den Speicherdialog zum Abspeichern des Memorys zu erhalten, genügt es die Zeile 311 in der Datei MemoryViewerTopComponent.java wie folgt anzupassen:

Putting in null is not cool. I defined the memory dump as .r2md files.

Thank you for bringing the issue up.
